name: XCalib
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - ultralytics
      - cupy-cuda12x
      - timm
      - huggingface_hub
      - seaborn
      - tqdm
      - jaxtyping
      - panda
      - scipy
      - git+https://github.com/Azorgz/ImagesCameras.git
