name: spacesampler
translation:
  minimum_delta: 0.01
  x:
    - 0.3
    - 2
  y:
    - 0.4
    - 2
  z:
    - 1
    - 5
rotation:
  minimum_delta: 0.01
  x:
    - 0.5
    - 1
  y:
    - 0.5
    - 1
  z:
    - 0
    - 0
focal_length:
  minimum_delta: 0.01
  values:
    - 0.2
    - 7
f_lambda:
  - 0.05
  - 0.001
